name: Feature Request
description: Request a feature
title: "[FEATURE] "
labels: [feature]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a feature! Please fill in the following details.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and detailed description of the feature request.
      placeholder: "Enter a clear and concise description of what the feature request is."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is the bug?
      options:
        - Critical
        - Major
        - Minor
    validations:
      required: true

  - type: textarea
    id: additional_info
    attributes:
      label: Additional Information
      description: Any other context or screenshots related to the bug.
      placeholder: "Enter additional context or information."
    validations:
      required: false
