import sys
from pathlib import Path

# Add project root to sys.path to allow running tests from this directory
# The project root is 6 levels up from the parent directory of this file.
project_root = str(Path(__file__).resolve().parents[6])
if project_root not in sys.path:
    sys.path.insert(0, project_root)

#
# This file is part of TEN Framework, an open source project.
# Licensed under the Apache License, Version 2.0.
# See the LICENSE file for more information.
#
import json
from unittest.mock import patch, AsyncMock
import os
import asyncio
import filecmp
import shutil
import threading

from ten_runtime import (
    ExtensionTester,
    TenEnvTester,
    Data,
)
from ten_ai_base.struct import TTSTextInput, TTSFlush


# ================ test dump ================
class ExtensionTesterDump(ExtensionTester):
    def __init__(self):
        super().__init__()
        # Use a fixed path as requested by the user.
        self.dump_dir = "./dump/"
        # Use a unique name for the file generated by the test to avoid collision
        # with the file generated by the extension.
        self.test_dump_file_path = os.path.join(
            self.dump_dir, "test_manual_dump.pcm"
        )
        self.audio_end_received = False
        self.received_audio_chunks = []

    def on_start(self, ten_env_tester: TenEnvTester) -> None:
        """Called when test starts, sends a TTS request."""
        ten_env_tester.log_info("Dump test started, sending TTS request.")

        tts_input = TTSTextInput(
            request_id="tts_request_1",
            text="hello word, hello agora",
            text_input_end=True,
        )
        data = Data.create("tts_text_input")
        data.set_property_from_json(None, tts_input.model_dump_json())
        ten_env_tester.send_data(data)
        ten_env_tester.on_start_done()

    def on_data(self, ten_env: TenEnvTester, data) -> None:
        name = data.get_name()
        if name == "tts_audio_end":
            ten_env.log_info("Received tts_audio_end, stopping test.")
            self.audio_end_received = True
            ten_env.stop_test()

    def on_audio_frame(self, ten_env: TenEnvTester, audio_frame):
        """Receives audio frames and collects their data using the lock/unlock pattern."""
        buf = audio_frame.lock_buf()
        try:
            copied_data = bytes(buf)
            self.received_audio_chunks.append(copied_data)
        finally:
            audio_frame.unlock_buf(buf)

    def write_test_dump_file(self):
        """Writes the collected audio chunks to a file."""
        with open(self.test_dump_file_path, "wb") as f:
            for chunk in self.received_audio_chunks:
                f.write(chunk)

    def find_tts_dump_file(self) -> str | None:
        """Find the dump file created by the TTS extension in the fixed dump directory."""
        if not os.path.exists(self.dump_dir):
            return None
        for filename in os.listdir(self.dump_dir):
            if filename.endswith(".pcm") and filename != os.path.basename(
                self.test_dump_file_path
            ):
                return os.path.join(self.dump_dir, filename)
        return None


@patch("speechify_tts_python.speechify_tts.SpeechifyTTSClient")
def test_dump_functionality(MockSpeechifyTTSClient):
    """Tests that the dump file from the TTS extension matches the audio received by the test extension."""

    print("Starting test_dump_functionality with mock...")

    DUMP_PATH = "./dump/"

    if os.path.exists(DUMP_PATH):
        shutil.rmtree(DUMP_PATH)
    os.makedirs(DUMP_PATH)

    mock_instance = MockSpeechifyTTSClient.return_value
    mock_instance.send_text = AsyncMock()
    mock_instance.close = AsyncMock()

    fake_audio_chunk_1 = b"\x11\x22\x33\x44" * 20
    fake_audio_chunk_2 = b"\xaa\xbb\xcc\xdd" * 20

    def mock_client_init(
        config, ten_env, error_callback=None, response_msgs=None
    ):
        mock_instance.response_msgs = (
            response_msgs if response_msgs else asyncio.Queue()
        )

        mock_synthesizer = AsyncMock()
        mock_synthesizer.send_text = AsyncMock()
        mock_synthesizer.send_text_in_connection = False
        mock_instance.synthesizer = mock_synthesizer

        async def populate_queue():
            await asyncio.sleep(0.01)
            await mock_instance.response_msgs.put(
                (fake_audio_chunk_1, False, "", 123)
            )
            await asyncio.sleep(0.01)
            await mock_instance.response_msgs.put(
                (fake_audio_chunk_2, True, "hello word, hello agora", None)
            )

        asyncio.create_task(populate_queue())
        return mock_instance

    MockSpeechifyTTSClient.side_effect = mock_client_init

    tester = ExtensionTesterDump()

    dump_config = {
        "params": {
            "key": "valid_api_key_for_test",
            "voice_id": "valid_voice_id_for_test",
            "dump": True,
            "dump_path": DUMP_PATH,
        },
    }

    tester.set_test_mode_single("speechify_tts_python", json.dumps(dump_config))

    try:
        print("Running dump test...")
        tester.run()
        print("Dump test completed.")

        assert tester.audio_end_received, "tts_audio_end was not received"

        tester.write_test_dump_file()
        assert os.path.exists(
            tester.test_dump_file_path
        ), "Test dump file was not created"

        tts_dump_file = tester.find_tts_dump_file()
        assert (
            tts_dump_file is not None
        ), f"Could not find TTS-generated dump file in {DUMP_PATH}"

        print(f"Comparing TTS dump file: {tts_dump_file}")
        print(f"With test dump file:    {tester.test_dump_file_path}")

        assert filecmp.cmp(
            tts_dump_file, tester.test_dump_file_path, shallow=False
        ), "The TTS dump file and the test-generated dump file do not match."

        print("Dump file binary comparison passed.")

    finally:
        if os.path.exists(DUMP_PATH):
            shutil.rmtree(DUMP_PATH)


# ================ test flush ================
class ExtensionTesterFlush(ExtensionTester):
    def __init__(self):
        super().__init__()
        self.ten_env: TenEnvTester | None = None
        self.audio_start_received = False
        self.first_audio_frame_received = False
        self.flush_start_received = False
        self.audio_end_received = False
        self.flush_end_received = False
        self.audio_end_reason = ""
        self.total_audio_duration_from_event = 0
        self.received_audio_bytes = 0
        self.sample_rate = 24000
        self.bytes_per_sample = 2  # 16-bit
        self.channels = 1
        self.audio_received_after_flush_end = False

    def on_start(self, ten_env_tester: TenEnvTester) -> None:
        self.ten_env = ten_env_tester
        ten_env_tester.log_info("Flush test started, sending long TTS request.")
        tts_input = TTSTextInput(
            request_id="tts_request_for_flush",
            text="This is a very long text designed to generate a continuous stream of audio, providing enough time to send a flush command.",
            text_input_end=True,
        )
        data = Data.create("tts_text_input")
        data.set_property_from_json(None, tts_input.model_dump_json())
        ten_env_tester.send_data(data)
        ten_env_tester.on_start_done()

    def on_audio_frame(self, ten_env: TenEnvTester, audio_frame):
        if self.flush_end_received:
            ten_env.log_error("Received audio frame after tts_flush_end!")
            self.audio_received_after_flush_end = True

        if not self.first_audio_frame_received:
            self.first_audio_frame_received = True
            ten_env.log_info("First audio frame received, sending flush data.")
            flush_data = Data.create("tts_flush")
            flush_data.set_property_from_json(
                None,
                TTSFlush(flush_id="tts_request_for_flush").model_dump_json(),
            )
            ten_env.send_data(flush_data)

        buf = audio_frame.lock_buf()
        try:
            self.received_audio_bytes += len(buf)
        finally:
            audio_frame.unlock_buf(buf)

    def on_data(self, ten_env: TenEnvTester, data) -> None:
        name = data.get_name()
        ten_env.log_info(f"on_data name: {name}")

        if name == "tts_audio_start":
            self.audio_start_received = True
            return

        if name == "tts_flush_start":
            self.flush_start_received = True
            return

        json_str, _ = data.get_property_to_json(None)
        if not json_str:
            return
        payload = json.loads(json_str)
        ten_env.log_info(f"on_data payload: {payload}")

        if name == "tts_audio_end":
            self.audio_end_received = True
            current_reason = payload.get("reason")
            if (
                self.audio_end_reason == 0 or current_reason == 2
            ):  # 2 = INTERRUPTED
                self.audio_end_reason = current_reason
            self.total_audio_duration_from_event = payload.get(
                "request_total_audio_duration_ms"
            )

        elif name == "tts_flush_end":
            self.flush_end_received = True

            def stop_test_later():
                ten_env.log_info("Waited after flush_end, stopping test now.")
                ten_env.stop_test()

            timer = threading.Timer(0.5, stop_test_later)
            timer.start()

    def get_calculated_audio_duration_ms(self) -> int:
        duration_sec = self.received_audio_bytes / (
            self.sample_rate * self.bytes_per_sample * self.channels
        )
        return int(duration_sec * 1000)


@patch("speechify_tts_python.speechify_tts.SpeechifyTTSClient")
def test_flush_logic(MockSpeechifyTTSClient):
    """
    Tests that sending a flush command during TTS streaming correctly stops
    the audio and sends the appropriate events.
    """
    print("Starting test_flush_logic with mock...")

    mock_instance = MockSpeechifyTTSClient.return_value
    mock_instance.send_text = AsyncMock()
    mock_instance.close = AsyncMock()

    cancel_event = asyncio.Event()

    def mock_cancel():
        cancel_event.set()

    mock_instance.cancel = mock_cancel

    def mock_client_init(
        config, ten_env, error_callback=None, response_msgs=None
    ):
        mock_instance.response_msgs = (
            response_msgs if response_msgs else asyncio.Queue()
        )

        mock_synthesizer = AsyncMock()
        mock_synthesizer.send_text = AsyncMock()
        mock_synthesizer.send_text_in_connection = True
        mock_instance.synthesizer = mock_synthesizer

        async def populate_queue():
            for _ in range(20):
                if cancel_event.is_set():
                    return

                await mock_instance.response_msgs.put(
                    (b"\x11\x22\x33" * 100, False, "", 123)
                )
                await asyncio.sleep(0.1)

            await mock_instance.response_msgs.put(
                (
                    b"\x44\x55\x66",
                    True,
                    "This is a very long text designed",
                    None,
                )
            )

        asyncio.create_task(populate_queue())
        return mock_instance

    MockSpeechifyTTSClient.side_effect = mock_client_init

    config = {"params": {"key": "valid_api_key", "voice_id": "valid_voice_id"}}
    tester = ExtensionTesterFlush()
    tester.set_test_mode_single("speechify_tts_python", json.dumps(config))

    print("Running flush logic test...")
    tester.run()
    print("Flush logic test completed.")

    assert tester.audio_start_received, "Did not receive tts_audio_start."
    assert tester.first_audio_frame_received, "Did not receive any audio frame."
    assert tester.audio_end_received, "Did not receive tts_audio_end."
    assert tester.flush_end_received, "Did not receive tts_flush_end."

    # A flushed stream ends with 'flush' reason (2 = INTERRUPTED)
    assert (
        tester.audio_end_reason == 2
    ), f"Expected audio end reason 'flush' (2), but got '{tester.audio_end_reason}'"

    calculated_duration = tester.get_calculated_audio_duration_ms()
    event_duration = tester.total_audio_duration_from_event
    print(
        f"Calculated duration: {calculated_duration}ms, Event duration: {event_duration}ms"
    )

    print("Flush logic test passed successfully.")
