version: '3'

tasks:
  build:
    desc: build the agent
    vars:
      AGENT: '{{.AGENT| default "examples/default"}}'
    cmds:
      - ln -s {{.AGENT}}/manifest.json .
      - ln -s {{.AGENT}}/property.json .
      - ./scripts/install_deps_and_build.sh linux x64 && mv bin/main bin/worker

  clean:
    desc: clean up
    cmds:
      - rm -rf manifest.json property.json bin/main bin/worker out ten_packages/system/ten_runtime* ten_packages/system/agora_rtc_sdk ten_packages/system/azure_speech_sdk ten_packages/system/nlohmann_json .release


