version: '3'

tasks:
  build:
    desc: build agents
    vars:
      AGENT: '{{.AGENT| default "examples/default"}}'
    cmds:
      - if [ ! -f manifest.json ]; then ln -s {{.AGENT}}/manifest.json . ; fi
      - if [ ! -f property.json ]; then ln -s {{.AGENT}}/property.json . ; fi
      - ./scripts/install_deps_and_build.sh linux x64 && mv bin/main bin/worker

  clean:
    desc: clean up agents
    cmds:
      - rm -rf manifest.json property.json manifest-lock.json bin/main bin/worker out ten_packages/system/ten_runtime* ten_packages/system/agora_rtc_sdk ten_packages/system/azure_speech_sdk ten_packages/system/nlohmann_json .release

  run:
    desc: run agents
    cmds:
      - ./bin/start
